import { createElement } from 'lwc';
import LWC_015_eg2_LWCLDS_Wire from 'c/lWC_015_eg2_LWCLDS_Wire';

describe('c-l-w-c-015-eg2-l-w-c-l-d-s-wire', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-015-eg2-l-w-c-l-d-s-wire', {
            is: LWC_015_eg2_LWCLDS_Wire
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});