// import { createElement } from 'lwc';
// import LWC_001_eg_LWCBasics from 'c/lWC_001_eg_LWCBasics';

// describe('c-l-w-c-001-eg-lwc-basics', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//     });

//     it('TODO: test case generated by CLI command, please fill in test logic', () => {
//         // Arrange
//         const element = createElement('c-l-w-c-001-eg-lwc-basics', {
//             is: LWC_001_eg_LWCBasics
//         });

//         // Act
//         document.body.appendChild(element);

//         // Assert
//         // const div = element.shadowRoot.querySelector('div');
//         expect(1).toBe(1);
//     });
// });