import { createElement } from 'lwc';
import LWC_011_eg1_LWCLDS_imp_Delete from 'c/lWC_011_eg1_LWCLDS_imp_Delete';

describe('c-l-w-c-011-eg1-l-w-c-l-d-s-imp-delete', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-011-eg1-l-w-c-l-d-s-imp-delete', {
            is: LWC_011_eg1_LWCLDS_imp_Delete
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});