// import { createElement } from 'lwc';
// import LWC_0100_eg3_mySecondLWCComponent from 'c/lWC_0100_eg3_mySecondLWCComponent';
// describe('c-l-w-c-0100-eg3-my-second-lwc-component', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//     });

//     it('TODO: test case generated by CLI command, please fill in test logic', () => {
//         // Arrange
//         const element = createElement('c-l-w-c-0100-eg3-my-second-lwc-component', {
//             is: LWC_0100_eg3_mySecondLWCComponent
//         });

//         // Act
//         document.body.appendChild(element);

//         // Assert
//         // const div = element.shadowRoot.querySelector('div');
//         expect(1).toBe(1);
//     });
// });