import { createElement } from 'lwc';
import LWC_005_eg1_Loop_and_Array from 'c/lWC_005_eg1_Loop_and_Array';

describe('c-l-w-c-005-eg1-loop-and-array', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-005-eg1-loop-and-array', {
            is: LWC_005_eg1_Loop_and_Array
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});