import { createElement } from 'lwc';
import LWC_010_eg1_LWCLDS_Imp_Create from 'c/lWC_010_eg1_LWCLDS_Imp_Create';

describe('c-l-w-c-010-eg1-l-w-c-l-d-s-imp-create', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-010-eg1-l-w-c-l-d-s-imp-create', {
            is: LWC_010_eg1_LWCLDS_Imp_Create
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});