import { createElement } from 'lwc';
import LWC_eg1_017_lwcevent_vlcplayer from 'c/lWC_eg1_017_lwcevent_vlcplayer';

describe('c-l-w-c-eg1-017-lwcevent-vlcplayer', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-eg1-017-lwcevent-vlcplayer', {
            is: LWC_eg1_017_lwcevent_vlcplayer
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});