import { createElement } from 'lwc';
import LWC_004_eg2_grater3num from 'c/lWC_004_eg2_grater3num';

describe('c-l-w-c-004-eg2-grater3-num', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-004-eg2-grater3-num', {
            is: LWC_004_eg2_grater3num
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});