public with sharing class Paymentservice {
    //  public static String processPayment(String paymentId) {
    //     // Example logic to process payment
    //     Payment__c payment = [SELECT Id, Amount__c FROM Payment__c WHERE Id = :paymentId LIMIT 1];
        
    //     if (payment.Amount__c > 0) {
    //         return 'Payment processed successfully';
    //     } else {
    //         return 'Invalid payment amount';
    //     }
    // }
}