import { createElement } from 'lwc';
import LWC_014_eg1_lwclds_wire_getcontact from 'c/lWC_014_eg1_lwclds_wire_getcontact';

describe('c-l-w-c-014-eg1-lwclds-wire-getcontact', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-014-eg1-lwclds-wire-getcontact', {
            is: LWC_014_eg1_lwclds_wire_getcontact
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});