import { createElement } from 'lwc';
import LWC_006_eg2_Loop_and_Array2 from 'c/lWC_006_eg2_Loop_and_Array2';

describe('c-l-w-c-006-eg2-loop-and-array2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-006-eg2-loop-and-array2', {
            is: LWC_006_eg2_Loop_and_Array2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});